CREATE DATABASE PLANES;

USE DATABASE PLANES;

CREATE TABLE USUARIO(
    NOMBRE VARCHAR(50) NOT NULL PRIMARY KEY,
    CONTRA VARCHAR(255) NOT NULL
);

CREATE TABLE PUBLI(
    TITULO VARCHAR(100) NOT NULL PRIMARY KEY,
    DESCRIP VARCHAR(255),
    F_INICIO VARCHAR(10) NOT NULL,
    F_FIN VARCHAR(10) NULL,
    NB VARCHAR(50),
    FOREIGN KEY (NB) REFERENCES USUARIO(NOMBRE)
);
