CREATE DATABASE PLANES;

USE DATABASE PLANES;

CREATE TABLE usuario(
    nombre VARCHAR(50) NOT NULL PRIMARY KEY,
    contra VARCHAR(255) NOT NULL
);

CREATE TABLE publi(
    titulo VARCHAR(100) NOT NULL PRIMARY KEY,
    descrip VARCHAR(255),
    f_inicio VARCHAR(10) NOT NULL,
    f_fin VARCHAR(10) NULL,
    nb VARCHAR(50),
    FOREIGN KEY (nb) REFERENCES USUARIO(nombre)
);
