CREATE DATABASE WE;

USE DATABASE WE;

CREATE TABLE USUARIO(
    NOMBRE VARCHAR(50) NOT NULL PRIMARY KEY,
    CONTRA VARCHAR(255) NOT NULL
);

CREATE TABLE PUBLI(
    TITULO VARCHAR(100) NOT NULL PRIMARY KEY,
    DESCRIP VARCHAR(255),
    TERMINADO VARCHAR(2) NOT NULL,
    NB VARCHAR(50),
    FOREIGN KEY (NB) REFERENCES USUARIO(NOMBRE)
);